export const catalogRestaurantSeeds = [
  {
    name: 'Restaurante El Tambello',
    cuisine: 'italian',
    priceRange: '$$',
    rating: 4.8,
    deliveryTime: '20-30 min',
    bannerImage: 'images/el_tambeno/tambeno_banner.jpg',
    logoImage: 'images/el_tambeno/el_tambeno_logo.png',
    address: 'Calle 123 #45-67, Centro',
    city: 'San Juan de Pasto',
    latitude: 1.21361,
    longitude: -77.28111,
    tags: ['italian', 'seafood', 'shareable'],
    isFeatured: true,
    isHot: true,
    description:
      'Carta amplia con platos de mar, carnes y entradas para compartir en un ambiente cálido.',
  },
  {
    name: 'Burger Lab',
    cuisine: 'fast',
    priceRange: '$',
    rating: 4.5,
    deliveryTime: '15-25 min',
    bannerImage: 'images/burguer_house/banner_burguer.jpg',
    logoImage: 'images/burguer_house/burguer_logo.png',
    address: 'Av. Siempre Viva #742',
    city: 'San Juan de Pasto',
    latitude: 1.22134,
    longitude: -77.28195,
    tags: ['fast', 'burger', 'combo'],
    isFeatured: true,
    isHot: true,
    description:
      'Hamburguesas con identidad propia, cocina directa y foco en ingredientes intensos.',
  },
  {
    name: 'Sazón Local',
    cuisine: 'local',
    priceRange: '$$',
    rating: 4.9,
    deliveryTime: '25-35 min',
    bannerImage: 'images/mi_restaurante/restaurante_banner1.jpg',
    logoImage: 'images/resto_papas/logoapp1.png',
    address: 'Carrera 15 #22-33',
    city: 'San Juan de Pasto',
    latitude: 1.2147,
    longitude: -77.27788,
    tags: ['local', 'traditional', 'comfort'],
    isFeatured: true,
    isHot: false,
    description:
      'Sabores de casa, platos abundantes y recetas tradicionales con presentación actual.',
  },
  {
    name: 'Veggie Heaven',
    cuisine: 'healthy',
    priceRange: '$$$',
    rating: 4.7,
    deliveryTime: '20 min',
    bannerImage: 'images/vegano/vegan_banner1.jpg',
    logoImage: 'images/vegano/logo__vegan.png',
    address: 'Calle 8 #12-34',
    city: 'San Juan de Pasto',
    latitude: 1.22629,
    longitude: -77.28592,
    tags: ['healthy', 'vegan', 'fresh'],
    isFeatured: true,
    isHot: false,
    description:
      'Cocina vegetal fresca con bowls, tostadas y platos ligeros pensados para repetir.',
  },
  {
    name: 'Mi Restaurante',
    cuisine: 'local',
    priceRange: '$$$',
    rating: 4.7,
    deliveryTime: '20 min',
    bannerImage: 'images/mi_restaurante/restaurante_banner1.jpg',
    logoImage: 'images/mi_restaurante/logo_restaurante.png',
    address: 'Boulevard Gastronómico 51',
    city: 'San Juan de Pasto',
    latitude: 1.22806,
    longitude: -77.27731,
    tags: ['local', 'premium', 'chef'],
    isFeatured: true,
    isHot: true,
    description:
      'Cocina casual premium con enfoque en experiencia de sala, productos nobles y servicio cuidado.',
  },
  {
    name: 'Papas Town',
    cuisine: 'fast',
    priceRange: '$',
    rating: 4.4,
    deliveryTime: '18-26 min',
    bannerImage: 'images/resto_papas/banner_papas.jpg',
    logoImage: 'images/resto_papas/logoapp1.png',
    address: 'Cra. 24 #18-41, San Juan de Pasto',
    city: 'San Juan de Pasto',
    latitude: 1.21543,
    longitude: -77.28364,
    tags: ['fast', 'street', 'papas'],
    isFeatured: false,
    isHot: true,
    description:
      'Papas cargadas, salsas fuertes y formato directo para pedidos rápidos y nocturnos.',
  },
  {
    name: 'Costa Brava Pasto',
    cuisine: 'local',
    priceRange: '$$',
    rating: 4.6,
    deliveryTime: '24-32 min',
    bannerImage: 'images/el_tambeno/tambeno_banner2.jpg',
    logoImage: 'images/el_tambeno/el_tambeno_logo.png',
    address: 'Calle 19 #30-15, San Juan de Pasto',
    city: 'San Juan de Pasto',
    latitude: 1.21854,
    longitude: -77.27321,
    tags: ['seafood', 'local', 'premium'],
    isFeatured: false,
    isHot: false,
    description:
      'Pescados, arroces y platos marinos con emplatado moderno y servicio orientado a delivery.',
  },
  {
    name: 'Trigo y Fuego',
    cuisine: 'local',
    priceRange: '$$',
    rating: 4.5,
    deliveryTime: '22-30 min',
    bannerImage: 'images/mi_restaurante/restaurante_banner3.jpg',
    logoImage: 'images/mi_restaurante/logo_restaurante.png',
    address: 'Av. Panamericana #12-90, San Juan de Pasto',
    city: 'San Juan de Pasto',
    latitude: 1.20984,
    longitude: -77.28971,
    tags: ['street', 'premium', 'comfort'],
    isFeatured: false,
    isHot: false,
    description:
      'Sándwiches calientes, bowls de autor y panadería salada con un perfil urbano.',
  },
] as const;

export const catalogDishSeeds = [
  {
    restaurantName: 'Restaurante El Tambello',
    name: 'Crispetas de pollo',
    description: 'Crujientes, jugosas y con salsa cremosa de la casa.',
    price: 12.99,
    imageUrl: 'images/el_tambeno/tambeno_plato1.jpg',
    isFeatured: true,
  },
  {
    restaurantName: 'Restaurante El Tambello',
    name: 'Rollo carne de res',
    description: 'Carne sazonada con perfil ahumado y guarnición crocante.',
    price: 14.99,
    imageUrl: 'images/el_tambeno/tambeno_plato2.jpg',
    isFeatured: true,
  },
  {
    restaurantName: 'Restaurante El Tambello',
    name: 'Chuleta de pescado',
    description: 'Pescado fresco con punto exacto de plancha y limón.',
    price: 14.99,
    imageUrl: 'images/el_tambeno/tambeno_plato3.jpg',
    isFeatured: false,
  },
  {
    restaurantName: 'Restaurante El Tambello',
    name: 'Seviche de camarones',
    description: 'Fresco, ácido y con textura firme en cada bocado.',
    price: 14.99,
    imageUrl: 'images/el_tambeno/tambeno_plato4.jpg',
    isFeatured: false,
  },
  {
    restaurantName: 'Burger Lab',
    name: 'Clásica Burger',
    description: 'Carne 180g, vegetales frescos y salsa secreta.',
    price: 9.99,
    imageUrl: 'images/burguer_house/banner_burguer2.jpg',
    isFeatured: true,
  },
  {
    restaurantName: 'Sazón Local',
    name: 'Tacos al pastor',
    description: 'Tres tacos con piña, cebolla y cilantro.',
    price: 8.99,
    imageUrl: 'images/mi_restaurante/restaurante_banner1.jpg',
    isFeatured: true,
  },
  {
    restaurantName: 'Veggie Heaven',
    name: 'Bowl vegano',
    description: 'Quinoa, aguacate y garbanzos con aderezo cremoso.',
    price: 11.99,
    imageUrl: 'images/vegano/vegan_banner1.jpg',
    isFeatured: true,
  },
  {
    restaurantName: 'Mi Restaurante',
    name: 'Plato especial',
    description: 'La firma de la casa con montaje limpio y sabores intensos.',
    price: 15.99,
    imageUrl: 'images/mi_restaurante/restaurante_banner1.jpg',
    isFeatured: true,
  },
  {
    restaurantName: 'Papas Town',
    name: 'Papas cargadas mixtas',
    description: 'Papas crocantes con cheddar, tocineta y salsa burger.',
    price: 13.5,
    imageUrl: 'images/resto_papas/banner_papas.jpg',
    isFeatured: true,
  },
  {
    restaurantName: 'Costa Brava Pasto',
    name: 'Arroz marinero',
    description: 'Arroz húmedo con camarón, pescado y fondo intenso.',
    price: 18.9,
    imageUrl: 'images/el_tambeno/tambeno_plato3.jpg',
    isFeatured: true,
  },
  {
    restaurantName: 'Trigo y Fuego',
    name: 'Sándwich de la casa',
    description: 'Pan tostado, proteína al grill y vegetales con salsa de ajo.',
    price: 14.2,
    imageUrl: 'images/mi_restaurante/restaurante_plato1.jpg',
    isFeatured: true,
  },
] as const;
